# Generated by Django 4.1.3 on 2022-12-06 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('a_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('a_title', models.CharField(max_length=30)),
                ('a_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
