# Generated by Django 4.1.3 on 2022-12-06 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yogaarticle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('c_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=300)),
                ('artic', models.CharField(max_length=300)),
            ],
        ),
    ]
